### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by eboileau** [eboileau/ribotools#2]
- [x] Use of IHW with LRT? Shrunken FC w/ and w/o LRT? (in older version I think shrinkage was turned off for LRT, but now is no longer default) -  BTW results with LRT doesn't require the `name`!
- [x] Allow finer-grain option selection (via config?)
- [x] Clean R scripts

---

- [x] STAR mapping with `gtf` + `de_novo_gtf` (also relevant for **Rp-Bp**)
- [x] #1 
- [x] Add minimal testing

There is very little we can do for unit testing, and many of the functionalities are directly taken from rpbp, so it doesn't make sense to test them here. We could do some sort of regression testing using a small test data, similar to rpbp. The advantage is that we could do comparisons with other methods, if needed, and provide data similar to [rpbp tutorials](https://rp-bp.readthedocs.io/en/latest/tutorial.html). I'm looking into [polyester](https://bioconductor.org/packages/release/bioc/vignettes/polyester/inst/doc/polyester.html) to simulate data.

All this would take a bit more time, but add value. I will open a separate issue in this case.

- [x] Finalise documentation, add RTD automating building, versioning

---

- [x] Add minimal GA CI that installs code & runs tests (add codecov integration for test coverage)

For testing, we leave it there for now, I don't want to implement a suite of regression testing that would mostly test Rp-Bp functionalities. See above. 

- [x] Add pre-commit to auto-format code
- [x] Add pypi deploy CI job
- [x] Release + package on bioconda

**Comment by eboileau** [comment]
- [x] The example dataset for tutorials (https://data.dieterichlab.org/s/dpFBSpczcxqGZDw) is not great... so we need to decide what to do.
- [x] When released and bioconda install tested incl. containers, update docs (installation).

**Comment by eboileau** [comment]
Tutorial data remains to do, at least we need to add some figures (docs).
